### ISSUE TITLE
results of supervised CIR method on this dataset

### ISSUE THREAD

**Issue by baiyang4** [miccunifi/CIRCO#1]
Hi there,

Thanks for your great work! I'm recently doing research on fully supervised CIR task. I'm wondering if you have any results of fully supervised CIR methods or baselin on this dataset.

BW

**Comment by LorenzoAgnolucci** [comment]
Hi @baiyang4!

Thanks for your interest in our work!

We did not provide any supervised baselines for CIRCO as we focused on Zero-Shot CIR. However, CIRCO could be employed also for testing the generalization capabilities of supervised CIR methods. 

You are more than welcome to test your supervised model on CIRCO! :)

Lorenzo
