### ISSUE TITLE
Evaluation server does not working

### ISSUE THREAD

**Issue by youngkyunJang** [miccunifi/CIRCO#2]
Hello, thanks for the wonderful work! 

Currently, the evaluation sever seems not working, can you please confirm on this?

Appreciated!

**Comment by LorenzoAgnolucci** [comment]
Hi @youngkyunJang,

Thanks for your interest in our work!

You are right, the server is currently not working due to some maintenance work in our lab. We will get the server back up and running ASAP. Sorry for the inconvenience.

**Comment by youngkyunJang** [comment]
Thanks for the quick response! Hope it recovers soon :)

**Comment by LorenzoAgnolucci** [comment]
Good news @youngkyunJang!

The server is now working correctly! Sorry again for the inconvenience.
